menu:
  Home: /
  Archives: /archives
  Github: https://github.com/NiaBie
  Link: /friends
  Knife: /knife
  Tags: /tags
  Categories: /categories

search:
	path: search.xml
	field: post
	content: true

local_search:
	enable: true # 搜索开关

auto_excerpt: # 自动摘要,不提供关闭的接口
  length: 300

debug:
  enable: false

mathjax: # 只能够通过在md中设置nomathjax != 0来关闭,默认开启,不会受站点配置文件控制
  enable: true
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML